[project]
name = "J.A.R.V.I.S. - Browser Agent"
version = "0.1.0"
description = "J.A.R.V.I.S. - Browser Agent"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "browser-use>=0.1.36",
    "click>=8.1.8",
    "langchain-openai>=0.3.1",
]
